version: '2'
services:
    killfomo-app:
        image: killfomo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://killfomo-mysql:3306/killfomo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    killfomo-mysql:
        extends:
            file: mysql.yml
            service: killfomo-mysql
